# Site settings
author: PasseRR
github: https://github.com/PasseRR
email: xie__hai@sina.com

# Build settings
highlighter: rouge
permalink: pretty

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
gems:
  - redcarpet
  - plantuml

# icon位置
icon: https://cdn.jsdelivr.net/gh/PasseRR/jekyll-ebook-theme/asserts/ico/favicon.ico